config/routes.rb
Rails.application.routes.draw do

 
  resources :city
  resources :gossip do 
    resources :comment
    resources :likes
  end
  
  resources :welcome
  resources :user
  resources :index
  resources :sessions, only:[:new, :create, :destroy, :index]


  get '/', to: 'index#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true
  #validates :zip_code, presence: true
  #, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" } 

end

app/models/cloud.rb
class Cloud < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :gossip, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  belongs_to :gossip
  belongs_to :tag, optional: true

  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :tags, through: :clouds
  has_many :likes, dependent: :destroy

  validates :title, presence: true,
  length: { minimum: 3, maximum: 14}
  #validates :content, presence: true 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :clouds

  validates :title, presence: true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  belongs_to :city, optional: true
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes, dependent: :destroy
  has_secure_password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
  validates :password, presence: true, length: { minimum: 6 }

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = Gossip.where(user_id:User.where(city_id:@city.id))
    @gossip = User.find_by(id: session[:user_id])
  end
  
  def new
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
  end
end

app/controllers/comment_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end
  
  def new
    # Pour revenir au gossip sur lequel on ajoute un commentaire
    @gossip = Gossip.find(params[:gossip_id]) 
    # Pour ajouter un commentaire
    @comment = Comment.new
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new(content: params[:content], gossip: @gossip)
  
    if @comment.save
      flash[:success] = "Comment successfully added! 👍"
      redirect_to gossip_path(@gossip.id)
    else
     redirect_to gossip_path(@gossip.id)
   end
  end
  
  
  def update
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
    
    if @comment.update(content: params[:content])  
      flash[:success] = "Gossip successfully modified! 👍"
      redirect_to gossip_path(@gossip.id)
    else
      render 'edit'
    end
  end
  
  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    
    
    @comment.destroy
    flash[:alert] = "Comment deleted! 🗑️"
    redirect_to gossip_path(@gossip.id)
  end
  
end
  

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/self_gossip_helper.rb
module SelfGossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    if session[:user_id]
      # même chose que hier

      current_user = User.find_by(id: session[:user_id])
      # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
      if user
      # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
        log_in(user)
        current_user = user
        end
  
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end 

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
    
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

app/views/comment/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-6 mx-auto">

      <h3 class="card-title text-center m-4">Editer un commentaire</h3>
      <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @comment.content, class: "form-control" %>
      <br/>

      <%= submit_tag "Confirm", class: "btn btn-primary" %>
            
      <%= link_to "Delete Comment", gossip_comment_path, data: {confirm: "Are you sure?"}, method: "delete", class: "btn btn-danger mb-0 ml-2" %>
      <% end %>
            
      <% if @comment.errors.any? %>

        <div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
          <p><strong>ERREUR ! Voici les raisons :</strong></p>
          <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            <% end %>
          </ul>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/comment/new.html.erb
<h1>Écrire un commentaire</h1>

<div class="container">

    
  <%= form_tag(gossip_comments_path(@id), method: "post") do %>
    <%= text_field_tag 'gossip_id', @id, type: 'hidden', class: 'form-control' %>
    <div class="form-group">
      <%= label_tag 'Nouveau commentaire' %>
      <%= text_area_tag 'content', '', required: true, class: 'form-control' %>
    </div>
    <%= submit_tag "Envoyer", class: 'btn btn-outline-primary btn-sm' %>
  <% end %>
                

</div>

app/views/comment/show.html.erb
<div class="list-group mx-auto">

  <% @gossip.comments.reverse.each do |comment| %>

    <div class="list-group-item mb-2">
      <div class="row">
        <div class="col-9">
          <p class="mb-1"><%= comment.content %></p>
        </div>
        <div class="col-3 text-right">
          <small><%= link_to "Edit", edit_gossip_comment_path(@gossip.id, comment.id) %></small>
        </div>
      </div>
    </div>
  <% end %>
  <div class="list-group mx-auto">

  <% @gossip.comments.reverse.each do |comment| %>

    <div class="list-group-item mb-2">
      <div class="row">
        <div class="col-9">
          <p class="mb-1"><%= comment.content %></p>
        </div>
        <div class="col-3 text-right">
          <small><%= link_to "Edit", edit_gossip_comment_path(@gossip.id, comment.id) %></small>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/comment/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>