config/routes.rb
Rails.application.routes.draw do

 
  resources :city
  resources :gossip do 
    resources :comment
    resources :likes
  end
  
  resources :welcome
  resources :user
  resources :index
  resources :sessions, only:[:new, :create, :destroy, :index]


  get '/', to: 'index#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true
  #validates :zip_code, presence: true
  #, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" } 

end

app/models/cloud.rb
class Cloud < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :gossip, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  belongs_to :gossip
  belongs_to :tag, optional: true

  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :tags, through: :clouds
  has_many :likes, dependent: :destroy

  validates :title, presence: true,
  length: { minimum: 3, maximum: 14}
  #validates :content, presence: true 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :clouds

  validates :title, presence: true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  belongs_to :city, optional: true
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes, dependent: :destroy
  has_secure_password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
  validates :password, presence: true, length: { minimum: 6 }

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips = Gossip.where(user_id:User.where(city_id:@city.id))
    @gossip = User.find_by(id: session[:user_id])
  end
  
  def new
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  before_action :authenticate_user, only: [:show,:new]

  def index
    @id = params[:id]
    @gossips = Gossip.all
  end

  def show
    @id = params[:id]
    @gossip = Gossip.find(params[:id])
    @comments = Gossip.find(params[:id]).content
    @comment = Comment.new(content: params['content'], gossip_id: 1, gossip_id: @gossip ,user_id: 1)
  end

  def new
    @gossip = Gossip.new    
  end

  def create
    @gossip = Gossip.create(title: params['title'], content: params['content'], user_id: 1)
    @gossip.user = User.find_by(id: session[:user_id])
    
    if @gossip.save 
      flash[:success] = "Gossip bien créé!"
      redirect_to welcome_index_path
    else
      flash[:danger] = "Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.join(" , ")}"
      render new_gossip_path
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(gossip_params)
    redirect_to gossip_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to welcome_index_path
  end
  
  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Veuillez vous connecter SVP!."
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/self_gossip_helper.rb
module SelfGossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    if session[:user_id]
      # même chose que hier

      current_user = User.find_by(id: session[:user_id])
      # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
      if user
      # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
        log_in(user)
        current_user = user
        end
  
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end 

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
    
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/edit.html.erb
<h1>Editer le Gossip</h1>

<%= form_for @gossip do |gossip|%>

  <div class = "form_group">
    <label>Titre du Gossip</label>
    <%= gossip.text_field :title, class: 'form_control' %>
  </div>

  <div class = "form_group">
    <label>Contenue du Gossip</label>
    <%= gossip.text_area :content, class: 'form_control' %>
  </div>

  <div class = "form_group">
    <button type="submit" class="btn btn-success">Modifier le Gossip</button>
  </div>

<%end%>

app/views/gossip/new.html.erb
<div class= "form ">
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <p><%= label_tag 'Titre' %></p>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <p><%= label_tag 'Contenue' %></p>
  <%= text_area_tag 'content', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Créer potin" %>
<% end %>
</div>

app/views/gossip/show.html.erb
<h1>The Gossip Page</h1>
<h2>Voici la page de :<a href="../user/<%= @gossip.id %>"> <%= @gossip.user.first_name%> </a></h2>

<p>Voici le contenu du gossip: <%= @gossip.content %></p>
<p> Notre ami(e) <%= @gossip.user.first_name%> vient de : <%= @gossip.user.city.name %></p>

<a href="/gossip/<%= @gossip.id %>" class="btn btn-danger btn-lg" data-confirm="êtes-vous sur?" data-method="DELETE">Supprimer le Gossip</a> 

<p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>

<% if pre_like %>
  <%= button_to 'Unlike', gossip_like_path(@gossip, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', gossip_likes_path(@gossip), method: :post %>
<% end %>

<div class="container">
    
 <%= form_tag(gossip_comment_path(@id), method: "post") do %>
    <%= text_field_tag 'gossip_id', @id, type: 'hidden', class: 'form-control' %>
     <div class="form-group">
         <p><%= label_tag 'Nouveau commentaire' %></p>
         </div>
         <%= text_area_tag 'content', '', required: true, class: 'form-control' %>
    <%= submit_tag "Envoyer", class: 'btn btn-success btn-lg' %>
 <% end %>                

</div>