config/routes.rb
Rails.application.routes.draw do

 
  resources :city
  resources :gossip do 
    resources :comment
    resources :likes
  end
  
  resources :welcome
  resources :user
  resources :index
  resources :sessions, only:[:new, :create, :destroy, :index]


  get '/', to: 'index#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true
  #validates :zip_code, presence: true
  #, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" } 

end

app/models/cloud.rb
class Cloud < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :gossip, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
  belongs_to :gossip
  belongs_to :tag, optional: true

  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :tags, through: :clouds
  has_many :likes, dependent: :destroy

  validates :title, presence: true,
  length: { minimum: 3, maximum: 14}
  #validates :content, presence: true 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :clouds

  validates :title, presence: true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  belongs_to :city, optional: true
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes, dependent: :destroy
  has_secure_password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
  validates :password, presence: true, length: { minimum: 6 }

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    if session[:user_id]
      # même chose que hier

      current_user = User.find_by(id: session[:user_id])
      # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
      if user
      # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
        log_in(user)
        current_user = user
        end
  
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end 

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
    
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/index/index.html.erb
 <nav>
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="btn btn-primary" <%= link_to "Team", team_path %></li>
    <li class="nav-item">
      <a class="btn btn-primary" <%= link_to "Contact", contact_path %></li>
    <li class="nav-item">
      <a class="btn btn-primary"<%= link_to "Publier un potin !", new_gossip_path %></li>
    <!--li class="nav-item"-->
      <!--a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a-->
    <!--</li>-->
  </ul>
</nav>
<h1>The Gossip Page</h1>

<h2>Voici tous les potins enregistrés!</h2>

<div class="row align-middle shadow p-3 mb-5 justify-content-center">

  <% @gossips.each_with_index do |gossip|%>

  <div class="card text-white bg-danger mb-3 text-center" style="min-width: 5rem;">

    <div class="card-header">Potin n°:<%= gossip.id%>
      <a href="gossip/<%= gossip.id %>" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Afficher potin</a>
  
    </div>
    <div class="card-body">
      <h5 class="card-title">Auteur: <%= gossip.user.first_name%></h5>
      <p class="card-text">Titre: <%= gossip.title %></p>
    </div>

  </div>
  
  <%end%>
</div>

app/views/index/show.html.erb
<h1>The Gossip Page</h1>

<h2>Voici tous les potins enregistrés!</h2>

<div class="row align-middle shadow p-3 mb-5 bg-body rounded">

  <%= @gossips.each_with_index do |gossip|%>

  <div class="card text-white bg-danger mb-3 text-center" style="max-width: 18rem;">
    <div class="card-header">Potin n°:<%= gossip.id%>
      <a href="gossip/<%= gossip.id %>" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Afficher potin</a>
    </div>

    <div class="card-body">
      <h5 class="card-title">Auteur: <%= gossip.user.first_name%></h5>
      <p class="card-text">Titre: <%= gossip.title %></p>
    </div>

  </div>
  
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipPojects</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <nav>
    <ul class="nav justify-content-center">
      <li class="nav-item">
      <% if current_user != nil%>
      <div class=nav justify-content-center>
        <h5>Bienvenue <%= current_user.first_name %></h5>
      </div>
      <li class="nav-item">
        <a class="btn btn-primary" <%= link_to "Accueil", welcome_index_path %></li>
      <li class="nav-create">
        <a class="btn btn-danger"  <%= link_to "Déconnexion", session_path(session.id), method: :delete %></li>
      <li class="nav-create">
      <%if current_user = nil%>
        <a class="btn btn-success"<%= link_to "Créer Utilisateur!", new_user_path %></li> 
      <%end%>
    </ul>
  </nav>
      <%else%>
  <div class="navbar-nav" >
    <nav>
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="btn btn-primary" <%= link_to "Home", index_index_path %></li>
        <li class="nav-item">
          <a class="btn btn-primary"  <%= link_to "Connexion", new_session_path %></li>
        <li class="nav-item">
          <a class="btn btn-primary"  <%= link_to "Inscription", new_user_path %></li>
      </ul>
    </nav>
  </div>
  <%end%>

  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
    <%= yield %>
  </body>
  
</html>